### ISSUE TITLE
Calculation of SNR metric

### ISSUE THREAD

**Issue by pcloudddd** [ubicomplab/rPPG-Toolbox#286] opened 2024-06-19 13:34 UTC
The figure below shows the SNR formula of JAMSNet(https://github.com/HongshengWang9/JAMSNet/blob/main/utils/get_SNR.m)
![image](https://github.com/ubicomplab/rPPG-Toolbox/assets/33437484/47f84a6d-cbff-4f2e-aecb-7074922a93a7)
Does the formula of SRN in rPPG-toolbox get a wrong simplfication?

**Comment by yahskapar** [comment] 2024-06-19 18:53
Hi @pcloudddd,

Can you elaborate on what you mean by "wrong simplification"? From what I can tell of the SNR implementation in JAMSNet, there are some differences (e.g., different frequency range considerations), but it would be surprising if there was alarming difference in computed SNR values. Have you noticed a significant difference and can you share these results in a follow-up reply so that I can try to reproduce it?

**Comment by pcloudddd** [comment] 2024-06-19 19:21
![20240620_031518](https://github.com/ubicomplab/rPPG-Toolbox/assets/33437484/4746665b-3d6c-4321-ab6d-e6dbf8c5e2ba)

**Comment by yahskapar** [comment] 2024-06-19 22:56
Hi @pcloudddd,

Thanks for the reply. One thing I want to note is the reference on that matter is at the very least incomplete and should really also refer to [this work](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7899506/) (again, see the bottom of page 6). I've noted this and will try to update this with the arXiv version sometime in the near future once I take another pass over that version.

Additionally, you are correct the formulas are presented differently, but as far as I can tell they lead to the same answer in the context of this repo. Have you noted otherwise? Let's take, for example, the two equations for SNR you presented in your previous reply - aren't they effectively the same given the [power rule for logarithms](https://byjus.com/maths/properties-of-logarithms/#power-rule) and with the terms [here](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/evaluation/post_process.py#L118)? 

Furthermore, let's say we compute `(signal_power_hm1 + signal_power_hm2) / signal_power_rem)` as 8.43 and then use that in each equation (effectively, feed it into a `mag2db` function). If you substitute the same value into each equation:

$10log_{10}(8.43^2) = 18.52$

$20log_{10}(8.43) = 18.52$

Same answers. Are you observing something different with your usage of JAMSNet or some other code? If so, it would be really helpful to compare results directly.

**Comment by pcloudddd** [comment] 2024-06-20 05:32
![20240620_133139](https://github.com/ubicomplab/rPPG-Toolbox/assets/33437484/7cce6726-f752-443a-978f-84c63fea691f)

**Comment by yahskapar** [comment] 2024-06-20 07:17
Hi @pcloudddd,

I see what you mean now, sorry for the confusion. That's a very fair point, and definitely more true to the equation in both references I mentioned before. I'll adjust the code in a coming PR to square the power terms and then properly use $10log_{10}$ instead of $20log_{10}$ due to dealing with powers. I'm not entirely sure what the origin of the toolbox's `mag2db` function was, will have to double-check that in case it was used anywhere outside of the SNR calculation.

**Comment by yahskapar** [comment] 2024-06-20 08:00
This will be addressed in #288, please feel free to take a look and thanks for pointing this out.

**Comment by yahskapar** [comment] 2024-06-21 23:31
This is fixed now with #288, I'll go ahead and close this issue. Feel free to make a new one if you have any other questions or concerns.

**Closed by yahskapar** 2024-06-21 23:31 UTC
