### ISSUE TITLE
ImportError: cannot import name '_iterative' from partially initialized module 'scipy.sparse.linalg.isolve' (most likely due to a circular import) (D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py)

### ISSUE THREAD

**Issue by dglzj** [ubicomplab/rPPG-Toolbox#258] opened 2024-03-19 08:09 UTC
Traceback (most recent call last):
  File "D:\rppg_toolbox\main_run.py", line 10, in <module>
    from dataset import data_loader
  File "D:\rppg_toolbox\dataset\data_loader\__init__.py", line 1, in <module>
    import dataset.data_loader.BaseLoader
  File "D:\rppg_toolbox\dataset\data_loader\BaseLoader.py", line 13, in <module>
    from scipy import signal
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\__init__.py", line 189, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "D:\Anaconda\envs\rppg-toolbox\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\signal\__init__.py", line 311, in <module>
    from . import _sigtools, windows
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\signal\windows\__init__.py", line 42, in <module>
    from ._windows import *
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\signal\windows\_windows.py", line 7, in <module>
    from scipy import linalg, special, fft as sp_fft
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\__init__.py", line 189, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "D:\Anaconda\envs\rppg-toolbox\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\linalg\__init__.py", line 225, in <module>
    from ._sketches import *
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\linalg\_sketches.py", line 9, in <module>
    from scipy.sparse import csc_matrix
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\sparse\__init__.py", line 287, in <module>
    from . import csgraph
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\sparse\csgraph\__init__.py", line 185, in <module>
    from ._laplacian import laplacian
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\sparse\csgraph\_laplacian.py", line 7, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\sparse\linalg\__init__.py", line 130, in <module>
    from . import isolve, dsolve, interface, eigen, matfuncs
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", line 4, in <module>
    from .iterative import *
  File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 8, in <module>
    from . import _iterative
ImportError: cannot import name '_iterative' from partially initialized module 'scipy.sparse.linalg.isolve' (most likely due to a circular import) (D:\Anaconda\envs\rppg-toolbox\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py)

I installed the environment according to the requirements file, but I get an error, how to solve it？thanks

**Comment by yahskapar** [comment] 2024-04-01 02:10
Hi @dglzj,

Are you still running into this issue? Have you tried manually reinstalling scipy using `pip uninstall` and then reinstalling with `pip install`? You can also try `pip --upgrade install` to see if updating any of the dependencies may help resolve the issue.

Unfortunately, I haven't been able to reproduce this issue on my end. If you're still running into this and the above advice hasn't helped, let us know of some more information, specifically:

1. What operating system are you on? 
2. Are you using a conda environment and following the setup instructions [here](https://github.com/ubicomplab/rPPG-Toolbox?tab=readme-ov-file#wrench-setup)? You mentioned you used the requirements file but it's not clear if you're doing this in a conda environment or not.
3. Can you confirm your Python version? You should be able to do this with `python --version`.
4. Can you copy/paste the output of `pip list`?

Thanks,

Akshay

**Comment by yahskapar** [comment] 2024-04-16 03:57
Hi @dglzj,

Given it's been two weeks since this issue has been active, I'll go ahead and close it. In case you are still encountering this issue, please feel free to comment again and we can look into it together.

Best regards,

Akshay

**Closed by yahskapar** 2024-04-16 03:57 UTC
