### ISSUE TITLE
In different state of PURE, POS,ICA,...methods show strange results.

### ISSUE THREAD

**Issue by Eadith** [ubicomplab/rPPG-Toolbox#141] opened 2023-04-19 04:05 UTC
I followed the setting of yours and test POS, ICA, CHROM, GREEN on PURE, the overall results is similar to yours. But when I show the results of different states of PURE, such as steady(01), talking(02),...,medium rotation(06), the results are strange as following:
===Unsupervised Method ( ICA ) Predicting ===
100%|███████████████████████████████████████████| 59/59 [02:19<00:00,  2.37s/it]
Used Unsupervised Method: ICA
State 01===>
Testing==> | me: -0.8789| std: 1.9653| mae: 1.0547| rmse: 2.1529| mer: 0.0138| p: 0.9963
State 02===>
Testing==> | me: -0.1953| std: 3.6067| mae: 2.3438| rmse: 3.6120| mer: 0.0404| p: 0.9900
State 03===>
Testing==> | me: -7.5586| std: 22.8666| mae: 8.3496| rmse: 24.0835| mer: 0.0715| p: 0.1075
State 04===>
Testing==> | me: -7.2070| std: 21.2272| mae: 8.7012| rmse: 22.4173| mer: 0.0827| p: 0.2836
State 05===>
**Testing==> | me: -0.6152| std: 1.8457| mae: 0.6152| rmse: 1.9455| mer: 0.0045| p: 0.9995**
State 06===>
Testing==> | me: -7.5586| std: 22.0926| mae: 7.5586| rmse: 23.3498| mer: 0.0585| p: 0.2988
State all===>
Testing==> | me: -4.0668| std: 16.2102| mae: 4.8116| rmse: 16.7125| mer: 0.0453| p: 0.7209
FFT MAE (FFT Label):4.811639300847458
FFT RMSE (FFT Label):16.71254207577304
FFT MAPE (FFT Label):4.534044786884735
FFT Pearson  (FFT Label):0.7208838648526229
===Unsupervised Method ( POS ) Predicting ===
100%|███████████████████████████████████████████| 59/59 [01:53<00:00,  1.93s/it]
Used Unsupervised Method: POS
State 01===>
Testing==> | me: 3.8672| std: 13.5089| mae: 5.4492| rmse: 14.0515| mer: 0.1107| p: 0.8198
State 02===>
Testing==> | me: 0.2930| std: 2.6204| mae: 1.2695| rmse: 2.6367| mer: 0.0241| p: 0.9948
State 03===>
**Testing==> | me: 0.1758| std: 0.5273| mae: 0.1758| rmse: 0.5559| mer: 0.0031| p: 0.9997**
State 04===>
Testing==> | me: 8.8330| std: 17.4286| mae: 8.8330| rmse: 19.5391| mer: 0.1773| p: 0.6721
State 05===>
Testing==> | me: 0.6152| std: 1.8457| mae: 0.6152| rmse: 1.9455| mer: 0.0096| p: 0.9971
State 06===>
Testing==> | me: 4.4824| std: 14.6408| mae: 5.1855| rmse: 15.3116| mer: 0.1013| p: 0.7947
State all===>
Testing==> | me: 3.0911| std: 11.4066| mae: 3.6274| rmse: 11.8180| mer: 0.0718| p: 0.8782
FFT MAE (FFT Label):3.627350370762712
FFT RMSE (FFT Label):11.817967292639915
FFT MAPE (FFT Label):7.180985775473761
FFT Pearson  (FFT Label):0.878197263199433
===Unsupervised Method ( GREEN ) Predicting ===
100%|███████████████████████████████████████████| 59/59 [01:20<00:00,  1.37s/it]
Used Unsupervised Method: GREEN
State 01===>
Testing==> | me: -5.0977| std: 13.3744| mae: 5.2734| rmse: 14.3130| mer: 0.0602| p: 0.8306
State 02===>
Testing==> | me: -9.5215| std: 21.2498| mae: 14.2090| rmse: 23.2855| mer: 0.1567| p: 0.5776
State 03===>
Testing==> | me: -7.9541| std: 23.8647| mae: 8.1299| rmse: 25.1554| mer: 0.0662| p: 0.0211
State 04===>
Testing==> | me: -9.5361| std: 20.6235| mae: 12.8760| rmse: 22.7215| mer: 0.1478| p: 0.3394
State 05===>
Testing==> | me: -6.6797| std: 26.9703| mae: 11.2500| rmse: 27.7851| mer: 0.1133| p: -0.1028
State 06===>
Testing==> | me: -8.2617| std: 26.0228| mae: 9.4922| rmse: 27.3027| mer: 0.0815| p: -0.0789
State all===>
Testing==> | me: -7.8133| std: 22.5463| mae: 10.1372| rmse: 23.8618| mer: 0.1034| p: 0.3410
FFT MAE (FFT Label):10.13721530720339
FFT RMSE (FFT Label):23.86176217201261
FFT MAPE (FFT Label):10.34061430399768
FFT Pearson  (FFT Label):0.34103255024699397
===Unsupervised Method ( LGI ) Predicting ===
100%|███████████████████████████████████████████| 59/59 [01:22<00:00,  1.40s/it]
Used Unsupervised Method: LGI
State 01===>
Testing==> | me: -5.1855| std: 13.3782| mae: 5.7129| rmse: 14.3480| mer: 0.0661| p: 0.8289
State 02===>
Testing==> | me: 0.5859| std: 2.9002| mae: 1.5625| rmse: 2.9588| mer: 0.0288| p: 0.9937
State 03===>
Testing==> | me: -7.1191| std: 22.0996| mae: 7.5586| rmse: 23.2179| mer: 0.0615| p: 0.1862
State 04===>
Testing==> | me: -9.6240| std: 22.8342| mae: 9.7119| rmse: 24.7795| mer: 0.0889| p: 0.1432
State 05===>
Testing==> | me: 1.5820| std: 4.7461| mae: 1.5820| rmse: 5.0028| mer: 0.0321| p: 0.9805
State 06===>
**Testing==> | me: 0.0879| std: 1.9034| mae: 0.9668| rmse: 1.9054| mer: 0.0144| p: 0.9973**
State all===>
Testing==> | me: -3.3443| std: 15.0113| mae: 4.5658| rmse: 15.3794| mer: 0.0490| p: 0.7719
FFT MAE (FFT Label):4.565843485169491
FFT RMSE (FFT Label):15.379369631243781
FFT MAPE (FFT Label):4.8959893981165665
FFT Pearson  (FFT Label):0.7719467652076283
===Unsupervised Method ( PBV ) Predicting ===
100%|███████████████████████████████████████████| 59/59 [01:20<00:00,  1.37s/it]
Used Unsupervised Method: PBV
State 01===>
Testing==> | me: -4.2188| std: 13.9012| mae: 5.9766| rmse: 14.5272| mer: 0.0720| p: 0.8161
State 02===>
Testing==> | me: -7.5195| std: 28.0459| mae: 13.7695| rmse: 29.0364| mer: 0.1468| p: 0.1160
State 03===>
**Testing==> | me: 0.1318| std: 0.8578| mae: 0.4834| rmse: 0.8679| mer: 0.0081| p: 0.9992**
State 04===>
Testing==> | me: 0.0439| std: 3.9475| mae: 1.8896| rmse: 3.9477| mer: 0.0322| p: 0.9836
State 05===>
Testing==> | me: 0.2637| std: 1.7600| mae: 0.7910| rmse: 1.7796| mer: 0.0158| p: 0.9974
State 06===>
Testing==> | me: -0.6152| std: 2.1185| mae: 1.3184| rmse: 2.2060| mer: 0.0216| p: 0.9958
State all===>
Testing==> | me: -1.8919| std: 12.8426| mae: 3.8731| rmse: 12.9812| mer: 0.0478| p: 0.8381
FFT MAE (FFT Label):3.8731461864406778
FFT RMSE (FFT Label):12.98118252450634
FFT MAPE (FFT Label):4.775171833897241
FFT Pearson  (FFT Label):0.8381165109607617
===Unsupervised Method ( CHROM ) Predicting ===
100%|███████████████████████████████████████████| 59/59 [01:20<00:00,  1.37s/it]
Used Unsupervised Method: CHROM
State 01===>
Testing==> | me: 8.3496| std: 18.1287| mae: 9.9316| rmse: 19.9591| mer: 0.2069| p: 0.6540
State 02===>
Testing==> | me: 1.8555| std: 5.2644| mae: 2.0508| rmse: 5.5818| mer: 0.0403| p: 0.9794
State 03===>
**Testing==> | me: 0.3955| std: 0.7971| mae: 0.3955| rmse: 0.8898| mer: 0.0062| p: 0.9993**
State 04===>
Testing==> | me: 8.7891| std: 17.4513| mae: 8.8770| rmse: 19.5396| mer: 0.1779| p: 0.6715
State 05===>
Testing==> | me: 4.1309| std: 14.5594| mae: 5.3613| rmse: 15.1340| mer: 0.1045| p: 0.8063
State 06===>
Testing==> | me: 6.5039| std: 15.2748| mae: 7.3828| rmse: 16.6018| mer: 0.1437| p: 0.7651
State all===>
Testing==> | me: 5.0574| std: 14.0384| mae: 5.7278| rmse: 14.9216| mer: 0.1145| p: 0.8091
FFT MAE (FFT Label):5.727787341101695
FFT RMSE (FFT Label):14.921567302513367
FFT MAPE (FFT Label):11.44912674073281
FFT Pearson  (FFT Label):0.8090882471300135
###############################################################################
For different traditional methods, there are some states show very good results (bold ones). If that happened to you, or did I make a mistake?

**Comment by yahskapar** [comment] 2023-04-29 07:31
I second @girishvn's advice regarding waveform investigation. Furthermore, I reproduced your POS result as follows:

Task 1:

FFT MAE (FFT Label):5.44921875
FFT RMSE (FFT Label):14.051509376984537
FFT MAPE (FFT Label):11.068468955155105
FFT Pearson  (FFT Label):0.819763620112126

Task 2:

FFT MAE (FFT Label):1.5625
FFT RMSE (FFT Label):2.779345599757365
FFT MAPE (FFT Label):2.856128922267984
FFT Pearson  (FFT Label):0.9944988176527765

Task 3:

FFT MAE (FFT Label):0.17578125
FFT RMSE (FFT Label):0.5558691199514729
FFT MAPE (FFT Label):0.3076923076923077
FFT Pearson  (FFT Label):0.9997049582245462

Task 4:

FFT MAE (FFT Label):8.8330078125
FFT RMSE (FFT Label):19.539115847728677
FFT MAPE (FFT Label):17.72977105413844
FFT Pearson  (FFT Label):0.6721043107184087

Task 5:

FFT MAE (FFT Label):0.615234375
FFT RMSE (FFT Label):1.9455419198301553
FFT MAPE (FFT Label):0.9589041095890409
FFT Pearson  (FFT Label):0.9970530304719605

Task 6:

FFT MAE (FFT Label):5.185546875
FFT RMSE (FFT Label):15.31164672965421
FFT MAPE (FFT Label):10.132463618679111
FFT Pearson  (FFT Label):0.7946806638191232

Appears to match aside from task 2. Can you double-check your task 2 results, as well as the data used for task 2? You should have 9 videos for task 2 in the PURE dataset. Aside from that, I think it's unlikely that you've introduced a bug on whatever branch you appear to be testing on. I agree that the MAE of ~0.175 for task 3 is quite low, but it's worth noting that you're only testing on 10 or so videos when testing on just a single task from PURE. Task 3 in particular is the "slow translation" task, so it makes sense in this case that the performance would be better compared to task 4, or the "fast translation" task, and reasonably low. Similar trend seems to appear between tasks 5 and 6, at least with POS. To me, it's more surprising that somehow task 1 has such poor performance compared to tasks 2, 3, and 5, but this could simply be because of differences in the ground truth for task 1 despite being a motion-less task, or some other factor that makes it more challenging for POS than tasks 2, 3, and 5.

**Comment by yahskapar** [comment] 2023-06-04 07:13
I'm going to go ahead and close this issue as no further discussion has occurred since the last post over a month ago. 

@Eadith, please feel free to make another issue if you happen to have any other observations you would like to share, or if you come across some behavior of the toolbox that you feel might be a bug. Thank you!

**Comment by yahskapar** [comment] 2023-06-04 07:13
I'm going to go ahead and close this issue as no further discussion has occurred since the last post over a month ago. 

@Eadith, please feel free to make another issue if you happen to have any other observations you would like to share, or if you come across some behavior of the toolbox that you feel might be a bug. Thank you!

**Closed by yahskapar** 2023-06-04 07:13 UTC
